CREATE TABLE users
(
    ID            BIGSERIAL PRIMARY KEY,
    NAME          VARCHAR(500) NOT NULL,
    PRIMARY_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    DATE_OF_BIRTH DATE         NOT NULL,
    PASSWORD      VARCHAR(500) NOT NULL,
    UNIQUE (ID)
);