CREATE TABLE accounts
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT  NOT NULL,
    BALANCE DECIMAL NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID)
);