CREATE TABLE accounts
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT  NOT NULL UNIQUE,
    BALANCE DECIMAL NOT NULL CHECK (BALANCE >= 0),
    FOREIGN KEY (USER_ID) REFERENCES users (ID) ON DELETE CASCADE
);