CREATE TABLE email_data
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT       NOT NULL,
    EMAIL   VARCHAR(200) NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES users (ID) ON DELETE CASCADE
);