CREATE TABLE phone_data
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT      NOT NULL,
    PHONE   VARCHAR(13) NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES users (ID) ON DELETE CASCADE
);