name: CI/CD Pipeline Backend

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["dev", "master"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check files
        run: echo "Checking files..."

  backend:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Back-end Automatic Tests
        run: ./mvnw test

      - name: Build backend
        run: ./mvnw clean package
